stages:
    - build

build-job:
  stage: build
  tags:
      - any-image-allowed
  image: python:3.11-alpine
  before_script:
      - pip install build
  script:
      - python -m build .
  artifacts:
      name: "MMISP-Worker Python Package"
      paths:
          - "dist/*.whl"
      expire_in: 1 hr
