stages:
    - build
    - deploy

build-job:
  stage: build
  tags:
      - any-image-allowed
  image: python:3.11-alpine
  before_script:
      - pip install build
  script:
      - python -m build .
  artifacts:
      name: "MMISP-Worker Python Package"
      paths:
          - "dist/*.whl"
      expire_in: 1 hr

deploy-to-staging-job:
    stage: deploy
    tags:
        - any-image-allowed
    image: alpine:latest
    before_script:
        - apt update && apt install scp
    variables:
        PACKAGE_NAME: find . -name "*.whl" | head -n 1 | xargs basename
    script:
        - scp -o StrictHostKeyChecking=no -i $SSH_KEY dist/*.whl root@worker.mmisp.cert.kit.edu:/root/
        - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@worker.mmisp.cert.kit.edu "
            pip install --force-reinstall $PACKAGE_NAME
            mmisp-worker
            disown
          "
    dependencies:
        - build-job
