
generate_mkdocs:
  before_script: []
  stage: docs
  image: hub.cert.kit.edu:5000/mkdocs
  script:
    - source /root/.venv/bin/activate; PYTHONPATH=src mkdocs build
  artifacts:
    paths:
      - site
  services:
    - name: plantuml/plantuml-server
      alias: plantuml
