default:
  tags:
      - any-image-allowed

variables:
  LIB_REPO_URL: https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.kit.edu/${CI_PROJECT_NAMESPACE}/lib.git
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  #  CI_DEBUG_SERVICES: true
  PYTHONUNBUFFERED: true

stages:
  - test
  - docs

cache:
  paths:
    - .cache/pip

generate_mkdocs:
  before_script: []
  stage: docs
  image: hub.cert.kit.edu:5000/mkdocs
  script:
    - source /root/.venv/bin/activate; PYTHONPATH=src mkdocs build
  artifacts:
    paths:
      - site
  services:
    - name: plantuml/plantuml-server
      alias: plantuml
