version: '3.8'

services:
  mmisp_worker:
    container_name: mmisp-worker
    build:
      context: .
    network_mode: host

    environment:
      - MMISP_API_HOST=0.0.0.0
      - MMISP_REDIS_HOST=localhost

    depends_on:
      - redis

  redis:
    container_name: mmisp-worker-redis
    image: redis:alpine
    network_mode: host
