site_name: Modern MISP API Documentation

theme:
  name: "material"

nav:
  - index.md

plugins:
  - search
  - mkdocstrings
  - plantuml:
      puml_url: http://plantuml:8080/
      num_workers: 4
  - build_plantuml:
      render: 'server'
      server: http://plantuml:8080
      output_format: svg
      diagram_root: docs/plantuml
  - with-pdf
