site_name: Modern MISP Worker Documentation

theme:
  name: "material"

nav:
  - index.md
  - Jobs:
    - Correlation: jobs/correlation.md
    - E-Mail: jobs/email.md
    - Enrichment: jobs/enrichment.md
    - Process Freetext: jobs/processfreetext.md
  - API: api.md
  - Config: config.md
  - Controller: controller.md
  - Exceptions: exceptions.md
  - MISP Database Adapter: misp_database.md

plugins:
  - search
  - mkdocstrings
  - plantuml:
      puml_url: http://plantuml:8080/
      num_workers: 4
  - build_plantuml:
      render: 'server'
      server: http://plantuml:8080
      output_format: svg
      diagram_root: docs/plantuml
  - to-pdf
