[project]
name = "mmisp-worker"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
requires-python = ">=3.11.0"


dependencies = [
  "fastapi==0.104.1",
  "pydantic==1.10.13",
  "uvicorn==0.24.0.post1",
  "celery",
  "redis"
]


[project.optional-dependencies]
dev = [
  "ruff==0.1.7",
  "pre-commit==3.6.0",
]


[project.scripts]
worker = "mmisp.worker.main:main"